version: "1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friends-challenge-api
    hostname: challenge_server
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
